name: Daily Database Cleanup

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Cleanup of stale jobs'
        required: false
        default: false
        type: boolean
  
  schedule:
    - cron: '0 1 * * *'

jobs:
  cleanup-database:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies with uv
        working-directory: ./agents
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run Database Cleanup
        working-directory: ./agents
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "🧹 Starting database cleanup at $(date)"
          uv run cleanup.py
          echo "✅ Database cleanup completed at $(date)"