name: Run Daily JobBot Agent

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run-job-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies with uv
        working-directory: ./agent
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --ci

      - name: Install Playwright browsers
        working-directory: ./agent
        run: playwright install chromium

      - name: Run JobBot Agent
        working-directory: ./agent
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
